name: CI
env:
  AWS_REGION_NAME: eu-central-1
  DEPLOY_PACKAGE_NAME: my_app_${{ github.sha }}.zip

on:
  push:
    branches:
      - main

jobs:
  test_app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run application
        run: python app.py
  
  deploy_lambda:
    runs-on: ubuntu-latest
    needs: [test_app]
    
    steps:
      - uses: actions/checkout@v2

       - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Create ZIP deployment package!
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Deploy
        run: aws lambda update-function-code --function-name=helloworldLambdaFunction --zip-file=fileb://${{ env.DEPLOY_PACKAGE_NAME }}